---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - domain_name is defined
      - docker_network_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined

- name: Create the dockernetwork
  docker_network:
    name: "{{ docker_network_name }}"

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "grafana/loki:latest"
    restart_policy: "always"
    cleanup: true
    pull: true
    exposed_ports:
      - 3100
    published_ports:
      - "0.0.0.0:3100:3100"  # map the port to the host's 3100 port
    networks:
      - name: "{{ docker_network_name }}"
      - name: "bridge"
      - name: "grafana_network"
    log_driver: "awslogs"
    log_options:
      awslogs-region: "{{ cloudwatch_region }}"
      awslogs-group: "{{ cloudwatch_log_group }}"
      awslogs-stream: "{{ application_name }}-{{ inventory_hostname }}"
    env:
      VIRTUAL_HOST: "{{ domain_name }}"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "3100"

- name: Restart proxy
  shell: 
    cmd: docker restart proxy
